name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Build
        run: ./scripts/buildprod.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud builds submit --tag europe-west10-docker.pkg.dev/notely-409220/notely-ar-repo/notely-image:mytag .'

      - name: 'Deploy to Cloud Run'
        run: gcloud run deploy notely --image europe-west10-docker.pkg.dev/notely-409220/notely-ar-repo/notely-image:mytag --region us-central1 --allow-unauthenticated --project notely-409220 --max-instances=4

